
POST http://localhost:4004/service/generator/generateTestCustomers
Content-Type: application/json

{
  "anzahl": 30
}
###

POST http://localhost:4004/service/generator/pushToBackend
Content-Type: application/json

{}